/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_michael_androidiotest_IOTest */

#ifndef _Included_com_michael_androidiotest_IOTest
#define _Included_com_michael_androidiotest_IOTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_michael_androidiotest_IOTest
 * Method:    writeTest
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_michael_androidiotest_IOTest_writeTest
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_michael_androidiotest_IOTest
 * Method:    readTest
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_michael_androidiotest_IOTest_readTest
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
